project:
  type: website
  output-dir: docs
  title: "Assignment8"

editor: visual

website:
  title: "Assignment8"
  navbar:
    left:
      - text: "Home"
        file: index.qmd

format:
  html:
    theme: cosmo

publish:
  gh-pages: true
